"""add loyalty config to restaurant

Revision ID: 769dd292416d
Revises: c5e6018d9d88
Create Date: 2026-03-09 22:52:15.298040

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '769dd292416d'
down_revision = 'c5e6018d9d88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restaurants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('loyalty_enabled', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('loyalty_points_per_unit', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('loyalty_redemption_value', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restaurants', schema=None) as batch_op:
        batch_op.drop_column('loyalty_redemption_value')
        batch_op.drop_column('loyalty_points_per_unit')
        batch_op.drop_column('loyalty_enabled')

    # ### end Alembic commands ###
