"""add default_language to restaurant

Revision ID: c5e6018d9d88
Revises: d2ef9e0f1072
Create Date: 2026-03-09 22:21:18.509097

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5e6018d9d88'
down_revision = 'd2ef9e0f1072'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restaurants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('default_language', sa.String(length=5), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restaurants', schema=None) as batch_op:
        batch_op.drop_column('default_language')

    # ### end Alembic commands ###
