"""add service_charge_amount to orders

Revision ID: d2ef9e0f1072
Revises: 8e02d7bb4c7a
Create Date: 2026-03-09 22:09:06.447861

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2ef9e0f1072'
down_revision = '8e02d7bb4c7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('service_charge_amount', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('service_charge_amount')

    # ### end Alembic commands ###
